### ISSUE TITLE
Sourcemaps are not downloaded/shown when I open the console

### ISSUE THREAD

**Issue by edaloicaro18** [coryhouse/js-dev-env-demo#3]
Hi Cory, I'm posting my question here because the discussion section in the Pluralsight page is not working for me. All my questions in your course appear to be posted in the web, but when I check the page from my mobile they're nowhere to be seen
![image](https://cloud.githubusercontent.com/assets/822043/20467230/1e8e4ad4-af51-11e6-94aa-3000276e3c1f.png)

Anyway, I've already finished your course, and I really enjoyed it. Learnt a lot! 
Unfortunately, there's a couple of things that didn't work for me like the part in which you show how to debug the minified version of a file using sourcemaps. I've tried with Chrome and Mozilla, with the code from the "Exercise Files" and with my own version, but I always end up with the transpiled, minified version of the file  ¯\_(ツ)_/¯ 

Do you have any idea what might be causing this?

**Comment by coryhouse** [comment]
Ouch, sorry the discussion board bug is biting you too. I cringe to think how many good questions have fallen through it's significant cracks.

Regarding the sourcemap issue, two things:
1. Have you tried the exercise file version I published? I know that one works.
2. Are you viewing the code through the browser tools as I show in the course? That way, the soucemaps will actually be parsed.

Thanks for the feedback! :)

**Comment by edaloicaro18** [comment]
Sorry for not getting back to you sooner.
Because I caught a really bad cold, I had to take a two-day sick leave and since I wanted to rest properly and focus on getting better I decided to completely stay away from any internet-related thing and that's why I didn't see your reply up until now :( 

Regarding your questions:

1.  Yes,  and it didn't work in Chrome and I thought it didn't work in Mozilla either, but when I later tried with the Mozilla built-in console ( previously I was trying with the firebug plugin) I realized it was actually working as expected.

2.  Yes, and for a moment you really made doubt whether I knew how to open the developer console XD 

Chrome:

![image](https://cloud.githubusercontent.com/assets/822043/20571572/fd6c8902-b175-11e6-8352-4770cbef7697.png)


Mozilla:

![image](https://cloud.githubusercontent.com/assets/822043/20571557/f29c292e-b175-11e6-9c52-a74f70f37186.png)

I think it must be a browser thing, because as the pictures show, it works in Mozilla.

**Comment by coryhouse** [comment]
It looks like it's working properly in both browsers in your screen shots. Are you all set now?

Glad you're feeling better!

**Comment by edaloicaro18** [comment]
But I thought that the sourcemaps should allow me see and debug the same code I wrote in ES6 and , although it's not very clear in the first screencap, what Chrome is showing is the bundle.js file  not the index.js file that I actually wrote.

In these new screen shots I put the debugger word next to the _import_ statements so that is easier for you too see that sourcemaps are actually not working the way they should.

Mozilla:

![image](https://cloud.githubusercontent.com/assets/822043/20604064/79ce7c50-b232-11e6-9bfe-1821ec759ae8.png)

Chrome:

![image](https://cloud.githubusercontent.com/assets/822043/20604130/d10df84c-b232-11e6-8bc0-24965737af3f.png)

Oh and thank you, I'm feeling much better now. 
Hope you're having a wonderful time with your loved ones. Happy thanksgiving!

**Comment by coryhouse** [comment]
Weird. You should see webpack listed under sources in Chrome too. It shows for me. Please share your full set up so I can try to repro.

**Comment by edaloicaro18** [comment]
I knew it was something in the browser. Doing a little bit of research I found that this option it's disabled by default :S 

![image](https://cloud.githubusercontent.com/assets/822043/20641679/2a8dfbf8-b3cb-11e6-9d12-1c90711f6dd5.png)

Having enabled that option, now everything works as expected

![image](https://cloud.githubusercontent.com/assets/822043/20641687/75539d0a-b3cb-11e6-91c3-ac0bc768a01b.png)

**Comment by coryhouse** [comment]
That's odd, because it was enabled by default for me on all my machines. Just set up my new Mac a week ago and it was on by default as well. I can't find any link saying this setting defaults to off. If you find anything, I'd love to read it.

Anyway, glad you're rolling!
